//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Super_QOI_converter__Console_ {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Super_QOI_converter__Console_.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Command: &quot;Super QOI converter&quot; [Paths to files or folders] [Options].
        /// </summary>
        internal static string Commands_title {
            get {
                return ResourceManager.GetString("Commands title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -c
        ///	Copy attributes and dates from original files.
        /// </summary>
        internal static string Copy_attributes_and_dates_option {
            get {
                return ResourceManager.GetString("Copy attributes and dates option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -d
        ///	Delete original files when finishing.
        /// </summary>
        internal static string Delete_source_option {
            get {
                return ResourceManager.GetString("Delete source option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -h, --help
        ///	Shows help.
        /// </summary>
        internal static string Help_option {
            get {
                return ResourceManager.GetString("Help option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -i
        ///	Ignore console colors.
        /// </summary>
        internal static string Ignore_colors_option {
            get {
                return ResourceManager.GetString("Ignore colors option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, that is an invalid option or an invalid path.
        /// </summary>
        internal static string Invalid_option_ot_path {
            get {
                return ResourceManager.GetString("Invalid option ot path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a to get more info about how to execute this program by console parameters.
        /// </summary>
        internal static string More_info_how_to_execute {
            get {
                return ResourceManager.GetString("More info how to execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It&apos;s not necessary to use this program with console commands, you can execute it by double-clicking on the executable file and you&apos;ll receive help to use it as an usual program. However, if you want to use it as console command, here&apos;s the necessary info:.
        /// </summary>
        internal static string Not_console_neccesary {
            get {
                return ResourceManager.GetString("Not console neccesary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Super QOI converter.
        /// </summary>
        internal static string Program_name {
            get {
                return ResourceManager.GetString("Program name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (console version).
        /// </summary>
        internal static string Specify_console_version {
            get {
                return ResourceManager.GetString("Specify console version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to.
        /// </summary>
        internal static string Welcome_to {
            get {
                return ResourceManager.GetString("Welcome to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must add path files to use these options!.
        /// </summary>
        internal static string You_must_add_paths {
            get {
                return ResourceManager.GetString("You must add paths", resourceCulture);
            }
        }
    }
}
